name: repo_viewer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #cupertino_icons: ^1.0.2
  oauth2: ^2.0.1
  flutter_secure_storage: ^4.2.0
  dartz: ^0.10.0-nullsafety.1
  dio: ^5.1.2
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  webview_flutter: ^4.2.0
  flash: ^3.0.3+5
  auto_route: ^7.1.0
  http: ^0.13.6
  material_design_icons_flutter: ^6.0.7096
  logger: ^1.3.0
  json_annotation: ^4.8.1
  sembast: ^3.4.4
  path_provider: ^2.0.15
  path: ^1.8.2
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  material_floating_search_bar: ^0.3.7
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  auto_route_generator: ^7.0.0
  build_runner: ^2.0.1

flutter:
  uses-material-design: true